POST http://127.0.0.1:3000/auth/register
Content-Type: application/json

{
    "name":"Ismael Vargas",
    "email": "wismael718@gmail.com",
    "password": "1234567",
    "telefono": "0962658076"
}


################
POST http://127.0.0.1:3000/categoria
Content-Type: application/json

{
    "nombreCategoria":"pantis",
    "detalle": "rojos"
}

################
GET  http://127.0.0.1:3000/categoria


#######
POST http://127.0.0.1:3000/auth/login
Content-Type: application/json

{
    "email": "wismael718@gmail.com",
    "password": "ismael"
}


#######
GET http://127.0.0.1:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Indpc21hZWw3MThAZ21haWwuY29tIiwiaWQiOjEsImlhdCI6MTczMzg4NjQ5MSwiZXhwIjoxNzMzODg3MDk2fQ.DbfrkHLj2SoFuduMakoGpsz2xjbeumaSPLMJrzAHvsY