##########################
POST http://127.0.0.1:3000/auth/forgot-password
Content-Type: application/json

{
    "email":"wismael718@gmail.com"
    
}

############
POST http://localhost:3000/auth/reset-password
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Indpc21hZWw3MThAZ21haWwuY29tIiwiaWF0IjoxNzM0MzAwOTQ3LCJleHAiOjE3MzQzMDQ1NDd9.-kTqwKtSmhFIVxOvSIkEWTyoz9ZoQ7XUQgwMh9NtCsg",
  "newPassword": "ismaela"
}